config/routes.rb
ThirdApp::Application.routes.draw do
resources :users

  match '/signup', to: 'users#new'

  match '/help', to: "static_pages#help"

  match '/about', to: "static_pages#about"

  match '/contact', to: "static_pages#contact"

  root :to => "static_pages#home"
  

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password 

before_save { |user| user.email = user.email.downcase }

  validates :name, presence: true, length: { maximum: 30}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[\w+\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX},
  	uniqueness: { case_sensitive: false }

  	validates :password, presence: true, length: {minimum: 5}
  	validates :password_confirmation, presence: true 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def show
  @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	# Returns the gravatar for the given user.
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class:"gravatar")
	end
end

app/views/layouts/_footer.html.erb
<footer class= 'footer'>
	<small>
		<a href="http://railsin20.org">Rails in 20 minutes</a> By Alfonso Rush
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></l1>
			<li><%= link_to "Contact", contact_path %></li>
	</nav>
</footer>

app/views/layouts/_header.html.erb
   <header class="navbar navbar-inverse navbar-fixed-top">
     	<div class="navbar-inner">
     	   <div class="container">
         <%= link_to "third app", root_path, id: "logo" %>
     	   <nav>
     	   	  <ul class="nav pull-right">
     	   	    <li><%= link_to "Home",     root_path %></li>
     	   	    <li><%= link_to "Help",     help_path %></li>
     	   	    <li><%= link_to "Sign in", '#' %></li>
              </ul>
     	   </nav>
     	</div>   
     </header>

     

app/views/layouts/_shim.html.erb
  <!--[if Lt IE 9]>
  <script src="http://html5shim.googlecode/svn/trunk/html5.js"></script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title)%> </title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
     <%= render 'layouts/header' %>
     <div class="container">
     	<%= yield %>
      <%= render 'layouts/footer' %>
      <% debug(params) if Rails.env.development? %>
     </div>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>

	<h1>About Us</h1>
	<p>This about us page content goes here</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Page') %>

	<h1>Contact Us</h1>
	<p>This Contact page content goes here</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help Page') %>


<h1>Help Page</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb

<% provide(:title, 'Home Page') %>
<div class="center hero-unit">
	<h1>Welcome to the Third App</h1>
	<p>This is the home page for the <a href = "https://railsin20minutes.org">Rails in 20 </a> Third sample application.</p>


	<%= link_to "Sign up now!",signup_path,class: "btn btn-large btn-primary" %>

</div>

<%= link_to image_tag("rails.png",alt: "Rails"), 'https://rubyonrails.org/' %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>


<h1>Sign up</h1>
<p>Place holer for the sign up page</p>

app/views/users/show.html.erb
<% provide(:title, @user.name) %> 
<div class = "row">
	<aside class = "span4">
		<section>
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %> 
			</h1>
		</section>
	</aside>
</div>